#!/usr/bin/env bash
# gen-coverage-matrix.sh
#
# Generates (or checks) docs/coverage-matrix.md — the honest, machine-derived
# statement of which static-analysis probe covers which language. The matrix is
# derived from each probe's actual `--include='*.ext'` list, so it cannot drift
# from reality: CI runs `--check` and fails if the committed matrix is stale.
#
# Usage:
#   gen-coverage-matrix.sh           # print the matrix to stdout
#   gen-coverage-matrix.sh --write   # write docs/coverage-matrix.md
#   gen-coverage-matrix.sh --check   # exit 1 if docs/coverage-matrix.md is stale
#
# bash 3.2+; requires python3.

set -u
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"

MATRIX=$(python3 <<'PY'
import os, re

# language label -> the extension that identifies it in a probe --include list
LANGS = [
    ("TS/JS", "ts"),
    ("Java", "java"),
    ("Kotlin", "kt"),
    ("Python", "py"),
    ("Go", "go"),
    ("Ruby", "rb"),
    ("C#", "cs"),
    ("PHP", "php"),
    ("Rust", "rs"),
]

# The text/grep probes whose coverage is language-specific.
TEXT_PROBES = [
    ("check-no-skipped-tests.sh", "committed `.skip`/`xit`/`t.Skip`/`#[ignore]`/etc."),
    ("check-no-sleep-waits.sh", "`sleep`/`Thread.Sleep`/`waitForTimeout`/`Task.Delay`"),
    ("check-config-externalized.sh", "hardcoded URLs/endpoints/secret literals"),
    ("check-observability-at-seams.sh", "boundary call with no log/metric/trace"),
    ("check-stateless-request-path.sh", "node-local mutable state on request path"),
    ("check-resilient-boundary.sh", "boundary call with no timeout/retry/fallback"),
]

# Structural probes: language-agnostic (operate on names/config/structure).
STRUCT_PROBES = [
    ("check-anti-dumping.sh", "forbidden dumping-ground names (any language)"),
    ("check-port-adapter-parity.sh", "`*.ports.*` without an adapter (any language)"),
    ("check-seam-contract-parity.sh", "declared seam missing Shape/Behavior (any language)"),
    ("check-sprint-id-collision.sh", "duplicate sprint id tokens (artifact, not code)"),
]

def includes(path):
    try:
        text = open(os.path.join("scripts", path)).read()
    except Exception:
        return set()
    return set(re.findall(r"--include='\*\.([a-z]+)'", text))

lines = []
lines.append("# Static-analysis coverage matrix")
lines.append("")
lines.append("> Generated by `scripts/gen-coverage-matrix.sh` from each probe's actual")
lines.append("> `--include` list. Do not edit by hand — CI (`--check`) fails if it is stale.")
lines.append("")
lines.append("Praxis is **language-agnostic in doctrine**. Its *static enforcement* is")
lines.append("**best-effort per language**, exactly as tabulated below. Structural probes")
lines.append("apply to every language; text probes apply to the languages they scan.")
lines.append("")
lines.append("## Text probes (language-specific)")
lines.append("")
header = "| Probe | " + " | ".join(l for l, _ in LANGS) + " |"
sep = "|" + "---|" * (len(LANGS) + 1)
lines.append(header)
lines.append(sep)
for probe, _desc in TEXT_PROBES:
    exts = includes(probe)
    # a language is covered if any of its identifying extensions is included
    cells = []
    for label, ext in LANGS:
        # TS/JS is a family; treat ts OR js as coverage
        covered = ext in exts or (label == "TS/JS" and ("ts" in exts or "js" in exts))
        cells.append("✓" if covered else "—")
    lines.append("| `%s` | %s |" % (probe, " | ".join(cells)))
lines.append("")
lines.append("## Structural probes (language-agnostic)")
lines.append("")
lines.append("| Probe | Applies to |")
lines.append("|---|---|")
for probe, desc in STRUCT_PROBES:
    lines.append("| `%s` | %s |" % (probe, desc))
lines.append("")
lines.append("## Reading this table")
lines.append("")
lines.append("- ✓ — the probe scans this language's files and has markers for it.")
lines.append("- — — not scanned; a violation in this language passes the probe silently.")
lines.append("- Adding a language = extend the `--include` list and markers in the text")
lines.append("  probes, then re-run `gen-coverage-matrix.sh --write`.")
print("\n".join(lines))
PY
)

TARGET="docs/coverage-matrix.md"
case "${1:-}" in
  --write)
    mkdir -p docs
    printf '%s\n' "$MATRIX" > "$TARGET"
    echo "wrote $TARGET"
    ;;
  --check)
    if [[ ! -f "$TARGET" ]]; then
      echo "gen-coverage-matrix: $TARGET missing; run --write" >&2
      exit 1
    fi
    if ! diff -q <(printf '%s\n' "$MATRIX") "$TARGET" >/dev/null; then
      echo "gen-coverage-matrix: $TARGET is stale; run 'scripts/gen-coverage-matrix.sh --write'" >&2
      diff <(printf '%s\n' "$MATRIX") "$TARGET" >&2 || true
      exit 1
    fi
    echo "gen-coverage-matrix: $TARGET is current"
    ;;
  *)
    printf '%s\n' "$MATRIX"
    ;;
esac
